// Departamentos y municipios de Colombia (DIVIPOLA) — fuente: paquete npm colombia-territorial (MIT).
// Usado para los selects de departamento/municipio en el formulario de casos, evitando errores de tipeo
// que rompían los filtros del mapa (que comparan strings exactos).
export const COLOMBIA: { nombre: string; municipios: string[] }[] = [
  {
    "nombre": "Amazonas",
    "municipios": [
      "El Encanto",
      "La Chorrera",
      "La Pedrera",
      "La Victoria",
      "Leticia",
      "Mirití-Paraná",
      "Puerto Alegría",
      "Puerto Arica",
      "Puerto Nariño",
      "Puerto Santander",
      "Tarapacá"
    ]
  },
  {
    "nombre": "Antioquia",
    "municipios": [
      "Abejorral",
      "Abriaquí",
      "Alejandría",
      "Amagá",
      "Amalfi",
      "Andes",
      "Angelópolis",
      "Angostura",
      "Anorí",
      "Anzá",
      "Apartadó",
      "Arboletes",
      "Argelia",
      "Armenia",
      "Barbosa",
      "Bello",
      "Belmira",
      "Betania",
      "Betulia",
      "Briceño",
      "Buriticá",
      "Caicedo",
      "Caldas",
      "Campamento",
      "Caracolí",
      "Caramanta",
      "Carepa",
      "Carmen de Viboral",
      "Carolina del Príncipe",
      "Caucasia",
      "Cañasgordas",
      "Chigorodó",
      "Cisneros",
      "Ciudad Bolívar",
      "Cocorná",
      "Concepción",
      "Concordia",
      "Copacabana",
      "Cáceres",
      "Dabeiba",
      "Donmatías",
      "Ebéjico",
      "El Bagre",
      "El Peñol",
      "El Retiro",
      "Entrerríos",
      "Envigado",
      "Fredonia",
      "Frontino",
      "Giraldo",
      "Girardota",
      "Granada",
      "Guadalupe",
      "Guarne",
      "Guatapé",
      "Gómez Plata",
      "Heliconia",
      "Hispania",
      "Itagüí",
      "Ituango",
      "Jardín",
      "Jericó",
      "La Ceja",
      "La Estrella",
      "La Pintada",
      "La Unión",
      "Liborina",
      "Maceo",
      "Marinilla",
      "Medellín",
      "Montebello",
      "Murindó",
      "Mutatá",
      "Nariño",
      "Nechí",
      "Necoclí",
      "Olaya",
      "Peque",
      "Pueblorrico",
      "Puerto Berrío",
      "Puerto Nare",
      "Puerto Triunfo",
      "Remedios",
      "Rionegro",
      "Sabanalarga",
      "Sabaneta",
      "Salgar",
      "San Andrés de Cuerquia",
      "San Carlos",
      "San Francisco",
      "San Jerónimo",
      "San José de la Montaña",
      "San Juan de Urabá",
      "San Luis",
      "San Pedro de Urabá",
      "San Pedro de los Milagros",
      "San Rafael",
      "San Roque",
      "San Vicente Ferrer",
      "Santa Bárbara",
      "Santa Fe de Antioquia",
      "Santa Rosa de Osos",
      "Santo Domingo",
      "Santuario",
      "Segovia",
      "Sonsón",
      "Sopetrán",
      "Tarazá",
      "Tarso",
      "Titiribí",
      "Toledo",
      "Turbo",
      "Támesis",
      "Uramita",
      "Urrao",
      "Valdivia",
      "Valparaíso",
      "Vegachí",
      "Venecia",
      "Yalí",
      "Yarumal",
      "Yolombó",
      "Yondó",
      "Zaragoza"
    ]
  },
  {
    "nombre": "Arauca",
    "municipios": [
      "Arauca",
      "Arauquita",
      "Cravo Norte",
      "Fortul",
      "Puerto Rondón",
      "Saravena",
      "Tame"
    ]
  },
  {
    "nombre": "Atlántico",
    "municipios": [
      "Baranoa",
      "Barranquilla",
      "Campo de la Cruz",
      "Candelaria",
      "Galapa",
      "Juan de Acosta",
      "Luruaco",
      "Malambo",
      "Manatí",
      "Palmar de Varela",
      "Piojó",
      "Polonuevo",
      "Ponedera",
      "Puerto Colombia",
      "Repelón",
      "Sabanagrande",
      "Sabanalarga",
      "Santa Lucía",
      "Santo Tomás",
      "Soledad",
      "Suan",
      "Tubará",
      "Usiacurí"
    ]
  },
  {
    "nombre": "Bogotá D.C.",
    "municipios": [
      "Bogotá"
    ]
  },
  {
    "nombre": "Bolívar",
    "municipios": [
      "Achí",
      "Altos del Rosario",
      "Arenal",
      "Arjona",
      "Arroyohondo",
      "Barranco de Loba",
      "Calamar",
      "Cantagallo",
      "Cartagena de Indias",
      "Cicuco",
      "Clemencia",
      "Córdoba",
      "El Carmen de Bolívar",
      "El Guamo",
      "El Peñón",
      "Hatillo de Loba",
      "Magangué",
      "Mahates",
      "Margarita",
      "María La Baja",
      "Mompox",
      "Montecristo",
      "Morales",
      "Norosí",
      "Pinillos",
      "Regidor",
      "Río Viejo",
      "San Cristóbal",
      "San Estanislao",
      "San Fernando",
      "San Jacinto",
      "San Jacinto del Cauca",
      "San Juan Nepomuceno",
      "San Martín de Loba",
      "San Pablo",
      "Santa Catalina",
      "Santa Rosa",
      "Santa Rosa del Sur",
      "Simití",
      "Soplaviento",
      "Talaigua Nuevo",
      "Tiquisio",
      "Turbaco",
      "Turbana",
      "Villanueva",
      "Zambrano"
    ]
  },
  {
    "nombre": "Boyacá",
    "municipios": [
      "Almeida",
      "Aquitania",
      "Arcabuco",
      "Belén",
      "Berbeo",
      "Betéitiva",
      "Boavita",
      "Boyacá",
      "Briceño",
      "Buenavista",
      "Caldas",
      "Campohermoso",
      "Cerinza",
      "Chinavita",
      "Chiquinquirá",
      "Chiscas",
      "Chita",
      "Chitaraque",
      "Chivatá",
      "Chivor",
      "Chíquiza",
      "Ciénega",
      "Coper",
      "Corrales",
      "Covarachía",
      "Cubará",
      "Cucaita",
      "Cuítiva",
      "Cómbita",
      "Duitama",
      "El Cocuy",
      "El Espino",
      "Firavitoba",
      "Floresta",
      "Gachantivá",
      "Garagoa",
      "Guacamayas",
      "Guateque",
      "Guayatá",
      "Gámeza",
      "Güicán",
      "Iza",
      "Jenesano",
      "Jericó",
      "La Capilla",
      "La Uvita",
      "La Victoria",
      "Labranzagrande",
      "Macanal",
      "Maripí",
      "Miraflores",
      "Mongua",
      "Monguí",
      "Moniquirá",
      "Motavita",
      "Muzo",
      "Nobsa",
      "Nuevo Colón",
      "Oicatá",
      "Otanche",
      "Pachavita",
      "Paipa",
      "Pajarito",
      "Panqueba",
      "Pauna",
      "Paya",
      "Paz de Río",
      "Pesca",
      "Pisba",
      "Puerto Boyacá",
      "Páez",
      "Quípama",
      "Ramiriquí",
      "Rondón",
      "Ráquira",
      "Saboyá",
      "Samacá",
      "San Eduardo",
      "San José de Pare",
      "San Luis de Gaceno",
      "San Mateo",
      "San Miguel de Sema",
      "San Pablo de Borbur",
      "Santa María",
      "Santa Rosa de Viterbo",
      "Santa Sofía",
      "Santana",
      "Sativanorte",
      "Sativasur",
      "Siachoque",
      "Soatá",
      "Socha",
      "Socotá",
      "Sogamoso",
      "Somondoco",
      "Sora",
      "Soracá",
      "Sotaquirá",
      "Susacón",
      "Sutamarchán",
      "Sutatenza",
      "Sáchica",
      "Tasco",
      "Tenza",
      "Tibaná",
      "Tibasosa",
      "Tinjacá",
      "Tipacoque",
      "Toca",
      "Togüí",
      "Tota",
      "Tunja",
      "Tununguá",
      "Turmequé",
      "Tuta",
      "Tutazá",
      "Tópaga",
      "Ventaquemada",
      "Villa de Leyva",
      "Viracachá",
      "Zetaquirá",
      "Úmbita"
    ]
  },
  {
    "nombre": "Caldas",
    "municipios": [
      "Aguadas",
      "Anserma",
      "Aranzazu",
      "Belalcázar",
      "Chinchiná",
      "Filadelfia",
      "La Dorada",
      "La Merced",
      "Manizales",
      "Manzanares",
      "Marmato",
      "Marquetalia",
      "Marulanda",
      "Neira",
      "Norcasia",
      "Palestina",
      "Pensilvania",
      "Pácora",
      "Riosucio",
      "Risaralda",
      "Salamina",
      "Samaná",
      "San José",
      "Supía",
      "Victoria",
      "Villamaría",
      "Viterbo"
    ]
  },
  {
    "nombre": "Caquetá",
    "municipios": [
      "Albania",
      "Belén de los Andaquíes",
      "Cartagena del Chairá",
      "Curillo",
      "El Doncello",
      "El Paujil",
      "Florencia",
      "La Montañita",
      "Milán",
      "Morelia",
      "Puerto Rico",
      "San José del Fragua",
      "San Vicente del Caguán",
      "Solano",
      "Solita",
      "Valparaíso"
    ]
  },
  {
    "nombre": "Casanare",
    "municipios": [
      "Aguazul",
      "Chámeza",
      "Hato Corozal",
      "La Salina",
      "Maní",
      "Monterrey",
      "Nunchía",
      "Orocué",
      "Paz de Ariporo",
      "Pore",
      "Recetor",
      "Sabanalarga",
      "San Luis de Palenque",
      "Sácama",
      "Tauramena",
      "Trinidad",
      "Támara",
      "Villanueva",
      "Yopal"
    ]
  },
  {
    "nombre": "Cauca",
    "municipios": [
      "Almaguer",
      "Argelia",
      "Balboa",
      "Bolívar",
      "Buenos Aires",
      "Cajibío",
      "Caldono",
      "Caloto",
      "Corinto",
      "El Tambo",
      "Florencia",
      "Guachené",
      "Guapí",
      "Inzá",
      "Jambaló",
      "La Sierra",
      "La Vega",
      "López de Micay",
      "Mercaderes",
      "Miranda",
      "Morales",
      "Padilla",
      "Patía",
      "Piamonte",
      "Piendamó",
      "Popayán",
      "Puerto Tejada",
      "Puracé",
      "Páez",
      "Rosas",
      "San Sebastián",
      "Santa Rosa",
      "Santander de Quilichao",
      "Silvia",
      "Sotará",
      "Sucre",
      "Suárez",
      "Timbiquí",
      "Timbío",
      "Toribío",
      "Totoró",
      "Villa Rica"
    ]
  },
  {
    "nombre": "Cesar",
    "municipios": [
      "Aguachica",
      "Agustín Codazzi",
      "Astrea",
      "Becerril",
      "Bosconia",
      "Chimichagua",
      "Chiriguaná",
      "Curumaní",
      "El Copey",
      "El Paso",
      "Gamarra",
      "González",
      "La Gloria",
      "La Jagua de Ibirico",
      "La Paz",
      "Manaure",
      "Pailitas",
      "Pelaya",
      "Pueblo Bello",
      "Río de Oro",
      "San Alberto",
      "San Diego",
      "San Martín",
      "Tamalameque",
      "Valledupar"
    ]
  },
  {
    "nombre": "Chocó",
    "municipios": [
      "Acandí",
      "Alto Baudó",
      "Atrato",
      "Bagadó",
      "Bahía Solano",
      "Bajo Baudó",
      "Bojayá",
      "Cantón de San Pablo",
      "Carmen del Darién",
      "Condoto",
      "Cértegui",
      "El Cantón del San Pablo",
      "El Carmen de Atrato",
      "El Litoral del San Juan",
      "Istmina",
      "Juradó",
      "Lloró",
      "Medio Atrato",
      "Medio Baudó",
      "Medio San Juan",
      "Nuquí",
      "Nóvita",
      "Quibdó",
      "Riosucio",
      "Río Iró",
      "Río Quito",
      "San José del Palmar",
      "San Juan",
      "Sipí",
      "Tadó",
      "Unguía",
      "Unión Panamericana"
    ]
  },
  {
    "nombre": "Córdoba",
    "municipios": [
      "Ayapel",
      "Buenavista",
      "Canalete",
      "Cereté",
      "Chimá",
      "Chinú",
      "Ciénaga de Oro",
      "Cotorra",
      "La Apartada",
      "Lorica",
      "Los Córdobas",
      "Momil",
      "Montelíbano",
      "Montería",
      "Morales",
      "Moñitos",
      "Planeta Rica",
      "Pueblo Nuevo",
      "Puerto Escondido",
      "Puerto Libertador",
      "Purísima",
      "Sahagún",
      "San Andrés de Sotavento",
      "San Antero",
      "San Bernardo del Viento",
      "San Carlos",
      "San José de Uré",
      "San Pelayo",
      "Tierralta",
      "Tuchín",
      "Valencia"
    ]
  },
  {
    "nombre": "Cundinamarca",
    "municipios": [
      "Agua de Dios",
      "Albán",
      "Almeidas",
      "Anapoima",
      "Apulo",
      "Arbeláez",
      "Arbeláez",
      "Beltrán",
      "Bituima",
      "Bojacá",
      "Cabrera",
      "Cachipay",
      "Cajicá",
      "Caparrapí",
      "Carmen de Carupa",
      "Chaguaní",
      "Chipaque",
      "Choachí",
      "Chocontá",
      "Chía",
      "Cogua",
      "Cota",
      "Cucunubá",
      "Cáqueza",
      "El Colegio",
      "El Peñón",
      "El Rosal",
      "Facatativá",
      "Fosca",
      "Funza",
      "Fusagasugá",
      "Fómeque",
      "Fúquene",
      "Gachancipá",
      "Girardot",
      "Granada",
      "Guaduas",
      "Guasca",
      "Guataquí",
      "Guatavita",
      "Guayabal de Síquima",
      "Gutiérrez",
      "Jerusalén",
      "La Calera",
      "La Mesa",
      "La Palma",
      "La Peña",
      "La Vega",
      "Lenguazaque",
      "Machetá",
      "Madrid",
      "Manta",
      "Medina",
      "Mosquera",
      "Nariño",
      "Nemocón",
      "Nilo",
      "Nocaíma",
      "Paime",
      "Pandi",
      "Paratebueno",
      "Pasca",
      "Puerto Salgar",
      "Pulí",
      "Quetame",
      "Quipile",
      "San Antonio del Tequendama",
      "San Bernardo",
      "San Cayetano",
      "San Francisco",
      "San Juan de Rioseco",
      "Sasaima",
      "Sesquilé",
      "Sibaté",
      "Silvania",
      "Simijaca",
      "Soacha",
      "Sopó",
      "Subachoque",
      "Suesca",
      "Supatá",
      "Susa",
      "Sutatausa",
      "Tabio",
      "Tausa",
      "Tena",
      "Tenjo",
      "Tibirita",
      "Tocaima",
      "Tocancipá",
      "Ubaque",
      "Ubaté",
      "Une",
      "Venecia",
      "Vergara",
      "Vianí",
      "Villa de San Diego de Ubaté",
      "Villapinzón",
      "Villeta",
      "Villeta",
      "Yacopí",
      "Zipacón",
      "Zipaquirá",
      "Útica"
    ]
  },
  {
    "nombre": "Guainía",
    "municipios": [
      "Barranco Minas",
      "Cacahual",
      "Inírida",
      "La Guadalupe",
      "Morichal Nuevo",
      "Pana Pana",
      "Puerto Colombia",
      "San Felipe"
    ]
  },
  {
    "nombre": "Guaviare",
    "municipios": [
      "Calamar",
      "El Retorno",
      "Miraflores",
      "San José del Guaviare"
    ]
  },
  {
    "nombre": "Huila",
    "municipios": [
      "Acevedo",
      "Agrado",
      "Aipe",
      "Algeciras",
      "Altamira",
      "Baraya",
      "Campoalegre",
      "Colombia",
      "Elías",
      "Garzón",
      "Gigante",
      "Guadalupe",
      "Hobo",
      "Isnos",
      "La Argentina",
      "La Plata",
      "Neiva",
      "Nátaga",
      "Oporapa",
      "Paicol",
      "Palermo",
      "Palestina",
      "Pital",
      "Pitalito",
      "Rivera",
      "Saladoblanco",
      "San Agustín",
      "Santa María",
      "Suaza",
      "Tarqui",
      "Tello",
      "Teruel",
      "Tesalia",
      "Timaná",
      "Villavieja",
      "Yaguará",
      "Íquira"
    ]
  },
  {
    "nombre": "La Guajira",
    "municipios": [
      "Albania",
      "Barrancas",
      "Dibulla",
      "Distracción",
      "El Molino",
      "Fonseca",
      "Hatonuevo",
      "La Jagua del Pilar",
      "Maicao",
      "Manaure",
      "Riohacha",
      "San Juan del Cesar",
      "Uribia",
      "Urumita",
      "Villanueva"
    ]
  },
  {
    "nombre": "Magdalena",
    "municipios": [
      "Algarrobo",
      "Aracataca",
      "Ariguaní",
      "Cerro de San Antonio",
      "Chivolo",
      "Ciénaga",
      "Concordia",
      "El Banco",
      "El Piñón",
      "El Retén",
      "Fundación",
      "Guamal",
      "Nueva Granada",
      "Pedraza",
      "Pijiño del Carmen",
      "Pivijay",
      "Plato",
      "Puebloviejo",
      "Remolino",
      "Sabanas de San Ángel",
      "Salamina",
      "San Sebastián de Buenavista",
      "San Zenón",
      "Santa Ana",
      "Santa Bárbara de Pinto",
      "Santa Marta",
      "Sitionuevo",
      "Tenerife",
      "Zapayán",
      "Zona Bananera"
    ]
  },
  {
    "nombre": "Meta",
    "municipios": [
      "Acacías",
      "Barranca de Upía",
      "Cabuyaro",
      "Castilla la Nueva",
      "Cubarral",
      "Cumaral",
      "El Calvario",
      "El Castillo",
      "El Dorado",
      "Fuente de Oro",
      "Granada",
      "Guamal",
      "La Macarena",
      "La Uribe",
      "Lejanías",
      "Mapiripán",
      "Mesetas",
      "Puerto Concordia",
      "Puerto Gaitán",
      "Puerto Lleras",
      "Puerto López",
      "Puerto Rico",
      "Restrepo",
      "San Carlos de Guaroa",
      "San Juan de Arama",
      "San Juanito",
      "San Martín",
      "Villavicencio",
      "Vista Hermosa"
    ]
  },
  {
    "nombre": "Nariño",
    "municipios": [
      "Albán",
      "Aldana",
      "Ancuya",
      "Arboleda",
      "Barbacoas",
      "Belén",
      "Buesaco",
      "Chachagüí",
      "Colón",
      "Consacá",
      "Contadero",
      "Cuaspud",
      "Cumbal",
      "Cumbitara",
      "Córdoba",
      "El Charco",
      "El Peñol",
      "El Rosario",
      "El Tablón de Gómez",
      "El Tambo",
      "Francisco Pizarro",
      "Funes",
      "Guachucal",
      "Guaitarilla",
      "Gualmatán",
      "Iles",
      "Imués",
      "Ipiales",
      "La Cruz",
      "La Florida",
      "La Llanada",
      "La Tola",
      "La Unión",
      "Leiva",
      "Linares",
      "Los Andes",
      "Magüí Payán",
      "Mallama",
      "Mosquera",
      "Nariño",
      "Olaya Herrera",
      "Ospina",
      "Pasto",
      "Policarpa",
      "Potosí",
      "Providencia",
      "Puerres",
      "Pupiales",
      "Ricaurte",
      "Roberto Payán",
      "Samaniego",
      "San Bernardo",
      "San Juan de Pasto",
      "San Lorenzo",
      "San Pablo",
      "San Pedro de Cartago",
      "Sandona",
      "Santa Bárbara",
      "Santacruz",
      "Sapuyes",
      "Taminango",
      "Tangua",
      "Tumaco",
      "Túquerres",
      "Yacuanquer"
    ]
  },
  {
    "nombre": "Norte de Santander",
    "municipios": [
      "Arboledas",
      "Bochalema",
      "Bucarasica",
      "Chinácota",
      "Chitagá",
      "Convención",
      "Cucutilla",
      "Cáchira",
      "Cácota",
      "Cúcuta",
      "Durania",
      "El Carmen",
      "El Tarra",
      "El Zulia",
      "Gramalote",
      "Hacarí",
      "Herrán",
      "La Esperanza",
      "La Playa de Belén",
      "Labateca",
      "Lourdes",
      "Mutiscua",
      "Ocaña",
      "Pamplona",
      "Pamplonita",
      "Puerto Santander",
      "Ragonvalia",
      "Salazar de Las Palmas",
      "San Calixto",
      "San Cayetano",
      "Santiago",
      "Sardinata",
      "Silos",
      "Teorama",
      "Tibú",
      "Toledo",
      "Villa Caro",
      "Villa del Rosario",
      "Ábrego"
    ]
  },
  {
    "nombre": "Putumayo",
    "municipios": [
      "Colón",
      "Mocoa",
      "Mocoa",
      "Orito",
      "Puerto Asís",
      "Puerto Caicedo",
      "Puerto Guzmán",
      "Puerto Leguízamo",
      "San Francisco",
      "San Miguel",
      "Santiago",
      "Sibundoy",
      "Valle del Guamuez",
      "Villagarzón"
    ]
  },
  {
    "nombre": "Quindío",
    "municipios": [
      "Armenia",
      "Buenavista",
      "Calarcá",
      "Circasia",
      "Córdoba",
      "Filandia",
      "Génova",
      "La Tebaida",
      "Montenegro",
      "Pijao",
      "Quimbaya",
      "Salento"
    ]
  },
  {
    "nombre": "Risaralda",
    "municipios": [
      "Apía",
      "Balboa",
      "Belén de Umbría",
      "Dosquebradas",
      "Guática",
      "La Celia",
      "La Virginia",
      "Marsella",
      "Mistrató",
      "Pereira",
      "Pueblo Rico",
      "Quinchía",
      "Santa Rosa de Cabal",
      "Santuario"
    ]
  },
  {
    "nombre": "San Andrés y Providencia",
    "municipios": [
      "Providencia y Santa Catalina Islas",
      "San Andrés"
    ]
  },
  {
    "nombre": "Santander",
    "municipios": [
      "Aguada",
      "Albania",
      "Aratoca",
      "Barbosa",
      "Barichara",
      "Barrancabermeja",
      "Betulia",
      "Bolívar",
      "Bucaramanga",
      "Cabrera",
      "California",
      "Capitanejo",
      "Carcasí",
      "Cepitá",
      "Cerrito",
      "Charalá",
      "Charta",
      "Chima",
      "Chipatá",
      "Cimitarra",
      "Concepción",
      "Confines",
      "Contratación",
      "Coromoro",
      "Curití",
      "El Carmen de Chucurí",
      "El Guacamayo",
      "El Peñón",
      "El Playón",
      "Encino",
      "Enciso",
      "Floridablanca",
      "Florián",
      "Galán",
      "Girón",
      "Guaca",
      "Guadalupe",
      "Guapotá",
      "Guavatá",
      "Gámbita",
      "Güepsa",
      "Hato",
      "Jesús María",
      "Jordán",
      "La Belleza",
      "La Paz",
      "Landázuri",
      "Lebrija",
      "Los Santos",
      "Macaravita",
      "Matanza",
      "Mogotes",
      "Molagavita",
      "Málaga",
      "Ocamonte",
      "Oiba",
      "Onzaga",
      "Palmar",
      "Palmas del Socorro",
      "Piedecuesta",
      "Pinchote",
      "Puente Nacional",
      "Puerto Parra",
      "Puerto Wilches",
      "Páramo",
      "Rionegro",
      "Sabana de Torres",
      "San Andrés",
      "San Benito",
      "San Gil",
      "San Joaquín",
      "San José de Miranda",
      "San Miguel",
      "San Vicente de Chucurí",
      "Santa Bárbara",
      "Santa Helena del Opón",
      "Simacota",
      "Socorro",
      "Suaita",
      "Sucre",
      "Suratá",
      "Tona",
      "Valle de San José",
      "Vetas",
      "Villanueva",
      "Vélez",
      "Zapatoca"
    ]
  },
  {
    "nombre": "Sucre",
    "municipios": [
      "Buenavista",
      "Caimito",
      "Chalán",
      "Colosó",
      "Corozal",
      "Coveñas",
      "El Roble",
      "Galeras",
      "Guaranda",
      "La Unión",
      "Los Palmitos",
      "Majagual",
      "Morroa",
      "Ovejas",
      "Palmito",
      "Sampués",
      "San Benito Abad",
      "San Juan de Betulia",
      "San Marcos",
      "San Onofre",
      "San Pedro",
      "Santiago de Tolú",
      "Sincelejo",
      "Sucre",
      "Tolú Viejo"
    ]
  },
  {
    "nombre": "Tolima",
    "municipios": [
      "Alpujarra",
      "Alvarado",
      "Ambalema",
      "Anzoátegui",
      "Armero",
      "Ataco",
      "Cajamarca",
      "Carmen de Apicalá",
      "Casabianca",
      "Chaparral",
      "Coello",
      "Coyaima",
      "Cunday",
      "Dolores",
      "El Espinal",
      "Falan",
      "Flandes",
      "Fresno",
      "Guamo",
      "Herveo",
      "Honda",
      "Ibagué",
      "Icononzo",
      "Lérida",
      "Líbano",
      "Mariquita",
      "Melgar",
      "Murillo",
      "Natagaima",
      "Ortega",
      "Palocabildo",
      "Piedras",
      "Planadas",
      "Prado",
      "Purificación",
      "Rioblanco",
      "Roncesvalles",
      "Rovira",
      "Saldaña",
      "San Antonio",
      "San Luis",
      "Santa Isabel",
      "Suárez",
      "Valle de San Juan",
      "Venadillo",
      "Villahermosa",
      "Villarrica"
    ]
  },
  {
    "nombre": "Valle del Cauca",
    "municipios": [
      "Alcalá",
      "Andalucía",
      "Ansermanuevo",
      "Argelia",
      "Bolívar",
      "Buenaventura",
      "Buga",
      "Bugalagrande",
      "Caicedonia",
      "Cali",
      "Calima",
      "Candelaria",
      "Cartago",
      "Dagua",
      "El Cairo",
      "El Cerrito",
      "El Dovio",
      "El Águila",
      "Florida",
      "Ginebra",
      "Guacarí",
      "Jamundí",
      "La Cumbre",
      "La Unión",
      "La Victoria",
      "Obando",
      "Palmira",
      "Pradera",
      "Restrepo",
      "Riofrío",
      "Roldanillo",
      "San Pedro",
      "Sevilla",
      "Toro",
      "Trujillo",
      "Tuluá",
      "Ulloa",
      "Versalles",
      "Vijes",
      "Yotoco",
      "Yumbo",
      "Zarzal"
    ]
  },
  {
    "nombre": "Vaupés",
    "municipios": [
      "Carurú",
      "Mitú",
      "Pacoa",
      "Papunaua",
      "Taraira",
      "Yavaraté"
    ]
  },
  {
    "nombre": "Vichada",
    "municipios": [
      "Cumaribo",
      "La Primavera",
      "Puerto Carreño",
      "Santa Rosalía"
    ]
  }
];

export const DEPARTAMENTOS = COLOMBIA.map(d => d.nombre);

export function municipiosDe(departamento: string): string[] {
  return COLOMBIA.find(d => d.nombre === departamento)?.municipios ?? [];
}
